---
abstract: 'Render simple UML class diagrams, by loading the code'
author:
  - 'Agent Zhang <agentzh@gmail.com>,'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: UML-Class-Simple
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Inspector: 1.16
  Devel::Peek: 0
  File::Slurp: 0
  File::Spec: 0
  IPC::Run3: 0
  List::MoreUtils: 0
  PPI: 0
  Template: 0
  XML::LibXML: 0
  YAML::Syck: 0
  perl: 5.004
version: 0.10
