---
abstract: 'Render simple UML class diagrams, by loading the code'
author:
  - "Yichun \"agentzh\" Zhang (ç« äº¦æ\x98¥) C<< <agentzh@gmail.com> >>, OpenResty Inc."
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.17'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UML-Class-Simple
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Inspector: '1.16'
  Devel::Peek: 0
  File::Slurp: 0
  File::Spec: 0
  IPC::Run3: 0
  List::MoreUtils: 0
  PPI: 0
  Template: 0
  XML::LibXML: 0
  YAML::Syck: 0
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/agentzh/uml-class-simple-pm
version: '0.22'
